Repository googleapis/python-media-translation, pull requests merged in 2021-04, with the labels that each got.

#38 chore: start tracking obsolete files
  synth.metadata
Labels: api: mediatranslation, cla: yes, context: full

#41 chore: add license headers
  .pre-commit-config.yaml
  docs/conf.py
  mediatranslation-v1beta1-py.tar.gz
  synth.metadata
Labels: api: mediatranslation, cla: yes, context: partial

#39 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .pre-commit-config.yaml
  docs/conf.py
  owlbot.py
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes

#44 chore: prevent normalization of semver versioning
  setup.py
Labels: api: mediatranslation, automerge, cla: yes
